using WpfPract1.FermaDataSetTableAdapters;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using WpfPract1;
using static System.Net.Mime.MediaTypeNames;

namespace WpfPract1
{
    public partial class personal : Window
    {
        personal_accountTableAdapter personal_AccountTableAdapter = new personal_accountTableAdapter();
        Biological_speciesTableAdapter bio_SpeciesTableAdapter = new Biological_speciesTableAdapter();
        public personal()
        {

            InitializeComponent();
            Pers_accDataGrid.ItemsSource = personal_AccountTableAdapter.GetDataBy1();
            species.ItemsSource = bio_SpeciesTableAdapter.GetData();
            species.DisplayMemberPath = "species_id";
            species.SelectedValuePath = "species_id";

        }
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            mainWindow.Show();
            Close();
        }
        private void Pers_accDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Pers_accDataGrid.Columns.First(x => x.Header == "bi_species_id").Visibility = Visibility.Hidden;
        }

        private void Button_Click_2(object sender, RoutedEventArgs e)
        {
            if ((Pers_accDataGrid.SelectedItem as DataRowView) != null)
            {
                personal_AccountTableAdapter.DeleteQuery(Convert.ToInt32((Pers_accDataGrid.SelectedItem as DataRowView).Row[0]));
                Pers_accDataGrid.ItemsSource = personal_AccountTableAdapter.GetDataBy1();
                MessageBox.Show("Удаление прошло успешно!");
                name.Text = "";
                poroda.Text = "";
                species.SelectedItem = null;
            }
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            if (name.Text != "" && poroda.Text != "" && species.SelectedItem != null)
            {
                personal_AccountTableAdapter.InsertQuery(name.Text, poroda.Text, Convert.ToInt32(species.Text));
                Pers_accDataGrid.ItemsSource = personal_AccountTableAdapter.GetDataBy1();
                name.Text = "";
                poroda.Text = "";
                species.SelectedItem = null;
            }
        }
        private void Button_Click_3(object sender, RoutedEventArgs e)
        {
            if ((Pers_accDataGrid.SelectedItem as DataRowView) != null && name.Text != "" && poroda.Text != "" && species.SelectedItem != null)
            {
                personal_AccountTableAdapter.UpdateQuery(name.Text, poroda.Text, Convert.ToInt32(species.Text), 
                    Convert.ToInt32((Pers_accDataGrid.SelectedItem as DataRowView).Row[0]), Convert.ToInt32((Pers_accDataGrid.SelectedItem as DataRowView).Row[3]));
                Pers_accDataGrid.ItemsSource = personal_AccountTableAdapter.GetDataBy1();
                MessageBox.Show("Изменение прошло успешно!");
                name.Text = "";
                poroda.Text = "";
                species.SelectedItem = null;
            }
        }

        private void Pers_accDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if ((Pers_accDataGrid.SelectedItem as DataRowView) != null)
            {
                name.Text = (Pers_accDataGrid.SelectedItem as DataRowView).Row[1].ToString();
                poroda.Text = (Pers_accDataGrid.SelectedItem as DataRowView).Row[2].ToString();
                species.Text = (Pers_accDataGrid.SelectedItem as DataRowView).Row[3].ToString();
            }
        }
    }
}

